name: Build 2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build
        run : |
          docker build . --file 2.Dockerfile --tag ketard/mcfarm-2:latest
      -
        name: Export
        run : |
          docker save ketard/mcfarm-2:latest -o ketard_mcfarm-2_latest.tar
          zstd -z --rm ketard_mcfarm-2_latest.tar
      -
        name: Publish
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: build-r2
          title: "Build 2"
          files: |
            ketard_mcfarm-2_latest.tar.zst
