name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build
        run : |
          docker build . --file Dockerfile --tag ketard/mcfarm:latest
      -
        name: Export
        run : |
          docker save ketard/mcfarm:latest -o ketard_mcfarm_latest.tar
          zstd -z --rm ketard_mcfarm_latest.tar
      -
        name: Publish
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: build-r1
          title: "Build"
          files: |
            ketard_mcfarm_latest.tar.zst
